services:
  - type: web
    name: boursia
    runtime: node
    buildCommand: cd frontend && npm install && npm run build && cd ../backend && npm install && npm run build
    startCommand: cd backend && node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
